const polishWords = [
	"porwać kogoś",
	"odrzucić, nie przyjmować",
	"pojawiać sie, wydawać się",
	"znikać",
	"odwaga",
	"dumny",
	"bogactwo",
	"funkcja, cecha, opcja",
	"uniknać, zapobieć",
	"pospiech, ruchy",
	"naprzód, do przodu",
	"cel, powód, przeznaczenie",
	"przypuszczać, domyślać sie",
	"obecny, bieżący, aktualny",
	"ulepszony, poprawiony",
	"zyskać, zdobywać, przyrost",
	"wydawać się, zdawać się",
	"dostrzec, zauważyć",
	"wypadek",
	"nagle, gwałtownie",
	"kierunek",
	"rozmyslać, rozważać",
	"kusić",
	"opłacający się, wart zachodu",
	"wymagać",
	"wyrok, osąd",
	"oceniać",
	"oceniać, określać",
	"potem, następnie",
	"mozliwości",
	"skorzystać z czegoś",
	"bać się, lękać się",
	"wycięczający",
	"wspomnieć, nadmieniać, zaznaczyć",
	"nadejść, zmieniać, nadchodzić",
	"połączyć, łączyć, wiązać",
	"nękanie",
	"razem",
	"wykonywać",
	"dostarczyć, udzielać, zaopatrzyć",
	"dodatkowy",
	"zapobiegać",
	"zarówno, bądź, albo",
	"odpowiadające",
	"następujące",
	"odzyskać, uratować",
	"etap, okres",
	"powyżej",
	"przeprowadzić, wykonywać",
	"przytoczyć",
	"wielka litera",
	"ułamek dziesiętny",
	"spojrzeć",
	"zmienić przypisanie",
	"komunikat, oświadczenie",
	"przydzielać",
	"dążyć",
	"kojarzyć, skojarzyć",
	"ostatnio, od niedawna",
	"prognoza",
	"dalej",
	"odnosić się",
	"wiązać",
	"sklep spożywczy",
	"obliczać",
	"odwoływać się do",
	"pod",
	"zagnieżdzony",
	"przewyższać, górować",
	"rozważać",
	"oszacować, oceniać",
	"przeciętny",
	"zamiar, cel",
	"płynnie",
	"majstrować",
	"gdziekolwiek",
	"pojemność, objętość",
	"pragnienie",
	"ogromny",
	"zwalił mnie z nóg",
	"pozostały",
	"naśladuje",
	"dokładnie",
	"próba",
	"nienormalny",
	"walka, bój",
	"przywilej",
	"nienawiść",
	"narozrabiać",
	"konieczność",
	"podpowiedź",
	"oszczędny",
	"doradzanie",
	"poza",
	"cytat",
	"robienie na drutach",
	"haft",
	"korepetytor, nauczyciel",
	"obcy, zagraniczny",
]
